---
title: "Spotify_songs"
author: ''
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)    # Biblioteka za manipulaciju podacima
library(readr)    # Biblioteka za čitanje podataka
library(stringr)  # Biblioteka za rad s nizovima znakova
library(tidyr)    # Biblioteka za rad s podacima u širem formatu
library(lubridate) # Biblioteka za rad s datumima
library(ggplot2)   # Biblioteka za vizualizaciju podataka

```

```{r}
df <- read.csv("spotify_songs.csv")  # Učitavanje podataka iz CSV datoteke "spotify_songs.csv"
head(df)                             # Prikaz prvih nekoliko redova podataka
glimpse(df)                          # Prikaz sažetih informacija o podacima
summary(df)                          # Prikaz osnovnih statističkih informacija o podacima

```


genre - energy
```{r}
ggplot(df, aes(x = playlist_genre, y = energy, fill = playlist_genre)) +
  geom_boxplot(color = "black") +
  labs(title = "Energy Distribution Across Playlist Genre", x = "Playlist Genre", y = "Energy") +
  scale_fill_manual(values = c("green", "green", "green", "green", "green", "green")) + 
  theme_minimal() +
  theme(legend.position = "none") 

ggsave("Genre-Energy.png", bg = "white")


```



```{r}
ggplot(df, aes(x = danceability, y = energy, color = track_popularity)) +
  geom_point(alpha = 0.9) +
  labs(title = "Danceability and Energy with Popularity Color", x = "Danceability", y = "Energy", color = "Popularity") +
  scale_color_continuous(name = "Popularity", low = "green", high = "red") +
  theme_minimal()

ggsave("Dance-Energy-popularity.png", bg = "white")



```


```{r}
df_subgenres <- df %>% group_by(playlist_genre, playlist_subgenre) %>% summarise(count = n())
ggplot(df_subgenres, aes(x = playlist_genre, y = count, fill = playlist_subgenre)) +
  geom_bar(stat = "identity", position = "stack", width = 0.95, color = "white") +
  labs(title = "Distribution of Genres with Subgenres", x = "Genre", y = "Count") +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 60, hjust = 1)
  ) +
  guides(fill = guide_legend(title = "Subgenre")) 


ggsave("Genre-Subgenre.png", bg = "white")


```

```{r}
top_artists <- df %>%
  group_by(track_artist) %>%
  summarise(avg_popularity = mean(track_popularity)) %>%
  top_n(10, avg_popularity)

ggplot(top_artists, aes(x = reorder(track_artist, -avg_popularity), y = avg_popularity, fill = track_artist)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 10 Artists Based on Popularity", x = "Artist", y = "Average Popularity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("Top 10 populari.png", bg = "white")

```




