---
title: "Seminar projek Spotify songs"
author: "Lovro Vuletić"
date: "`r Sys.Date()`"
output:
  html_document: default
---

```{r include=FALSE}
library(tidyverse)
library(gridExtra)
library(GGally)
library(dplyr)
library(readr)
library(stringr)
library(hflights)
library(tidyr)
library(lubridate)
library(ggplot2)
library(emojifont)
library(RColorBrewer)

knitr::opts_chunk$set(results = 'hold')
```


```{r, echo = T}


spotify <- read.csv("spotify_songs.csv")

spotify %>% select(-c(playlist_id, playlist_genre, playlist_subgenre, playlist_name)) %>% distinct() -> spotify_filtered

#spotify3 <- spotify %>%
  #filter(track_artist == "Tones and I")


#spotify3 <- spotify %>%
  #arrange(desc(track_popularity))




```




```{r, echo = T}
#top 10 najpopularnijih albuma

spotify <- read.csv("spotify_songs.csv")

spotify %>% select(-c(playlist_id, playlist_genre, playlist_subgenre, playlist_name)) %>% distinct() -> spotify_filtered



spotify_filtered$Num_of_Songs_in_album <- ave(rep(1, nrow(spotify_filtered)), spotify_filtered$track_album_name, FUN = length)


spotify2 <- spotify_filtered %>%
  group_by(track_album_name) %>%
  summarize(Num_of_Songs_in_album = n(),
            Zbroj_track_popularity = sum(track_popularity))

spotify2 <- spotify2 %>%
  filter(Num_of_Songs_in_album >= 5)

spotify2 <- spotify2 %>%
  mutate(average_popularity = Zbroj_track_popularity / Num_of_Songs_in_album)

spotify2_sortirano <- spotify2 %>%
  arrange(desc(average_popularity))

top_10_albuma <- spotify2_sortirano %>%
  slice_head(n = 10)

top_10_albuma

ggplot(top_10_albuma, aes(x = reorder(track_album_name, -average_popularity), y = average_popularity, col = track_album_name)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  labs(title = "Top 10 Albums By Song Popularity",
       x = "Name of the Album",
       y = "Average Song Popularity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), ) +
  scale_y_continuous(breaks = seq(0,100, 10), limits = c(0, 100)) +
   annotate("text", x = Inf, y = -Inf, hjust = 1, vjust = 0,
           label = "Only Albums With 5 or More Tracks", size = 3)

ggsave("grad2.png")

```


```{r, echo = T}
#top 10 najpopularnijih playlista

spotify <- read.csv("spotify_songs.csv")

spotify2 <- spotify %>%
  group_by(playlist_name)

spotify2 <- spotify2 %>%
  summarise(
    playlist_genre = first(playlist_genre),
    popularity = sum(track_popularity),
    Num_of_songs = n()
  )

spotify2 <- spotify2 %>%
  filter(Num_of_songs >= 5)

spotify2 <- spotify2 %>%
  arrange(desc(popularity), Num_of_songs)

top_10_playlist <- spotify2 %>%
  slice_head(n = 10)

top_10_playlist <- top_10_playlist %>%
  mutate(playlist_genre = case_when(
    playlist_genre == "latin" ~ "Latin",
    playlist_genre == "pop" ~ "Pop",
    playlist_genre == "r&b" ~ "R&B",
    playlist_genre == "rock" ~ "Rock",
    TRUE ~ playlist_genre
  ))



top_10_playlist

as.factor(top_10_playlist$playlist_name)
top_10_playlist$playlist_name[1] <- "2020 Hits & 2019  Hits – Top Global Tracks"
top_10_playlist$playlist_name[4] <- "Charts 2020 Top 2020 Hits 2020 Summer 2020"

top_10_playlist

ggplot(top_10_playlist, aes(x = reorder(playlist_name, -popularity), y = popularity, fill = playlist_genre)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Top 10 Playlists by Popularity",
       x = "Name of the Playlist",
       y = "Popularity", fill = "Genre") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 8)) +
  scale_y_continuous(breaks = seq(0, 20547, 5000)) + 
  coord_flip() 
 

   ggsave("graf2.png")

```
```{r, echo = T}
#odnos energije i populrnosti pjesme

spotify <- read.csv("spotify_songs.csv")

spotify %>% select(-c(playlist_id, playlist_genre, playlist_subgenre, playlist_name)) %>% distinct() -> spotify_filtered



spotify2 <- spotify_filtered %>% select(track_name, track_popularity, energy)

spotify2 <- spotify2 %>%
  mutate(popularity_interval = cut(track_popularity, breaks = seq(0, 100, 2)))


average_energy_by_interval <- spotify2 %>%
  group_by(popularity_interval) %>%
  summarise(average_energy = mean(energy, na.rm = TRUE))

average_energy_by_interval

# Stvaranje grafa bez legende s prilagođenim intervalima na x-osi
ggplot(average_energy_by_interval, aes(x = popularity_interval, y = average_energy, group = 1)) +
  geom_line(color = "firebrick2", size = 1.5) +
  labs(x = "Popularity", y = "Energy") +
  ggtitle("The Energy of the Song and its Popularity") +
  theme_bw() +
  theme(legend.position = "none") +
  scale_x_discrete(labels = seq(0,100, 2)) +
  scale_y_continuous(limits = c(0.3, 1), breaks = seq(0, 1, 0.1))
  

  ggsave("graf3.png")
```
```{r, echo = T}
#odnos dancibilitya i populrnosti pjesme


spotify <- read.csv("spotify_songs.csv")

spotify %>% select(-c(playlist_id, playlist_genre, playlist_subgenre, playlist_name)) %>% distinct() -> spotify_filtered

spotify2 <- spotify_filtered %>% select(track_name, track_popularity, danceability)

spotify2 <- spotify2 %>%
  mutate(popularity_interval = cut(track_popularity, breaks = seq(0, 100, 2)))


average_energy_by_interval <- spotify2 %>%
  group_by(popularity_interval) %>%
  summarise(average_danceability = mean(danceability, na.rm = TRUE))

average_energy_by_interval

# Stvaranje grafa bez legende s prilagođenim intervalima na x-osi
ggplot(average_energy_by_interval, aes(x = popularity_interval, y = average_danceability, group = 1)) +
  geom_line(color = "firebrick2", size = 1.5) +
  labs(x = "Popularity", y = "Danceability") +
  ggtitle("The Danceability of the Song and its Popularity") +
  theme_bw() +
  theme(legend.position = "none") +
  scale_x_discrete(labels = seq(0,100, 2)) +
  scale_y_continuous(limits = c(0.3, 1), breaks = seq(0, 1, 0.1))
  

  ggsave("graf4.png")
```